#  _   _                  _                 _  
# | | | |_   _ _ __  _ __| | __ _ _ __   __| | 
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` | 
# |  _  | |_| | |_) | |  | | (_| | | | | (_| | 
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_| 
#        |___/|_|                              
# 

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf



# ------------------------------------------------------
# Monitors
# ------------------------------------------------------

source = ~/.config/hypr/conf/monitors.conf



# ------------------------------------------------------
# My Programs
# ------------------------------------------------------

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
#$fileManager = nautilus 
$fileManager = kitty -e yazi      # opens a new terminal and executes yazi (cli file manager)
#$menu = wofi --show drun --allow-images -D key_expand=Tab -s ~/.config/wofi/style.css
$menu = rofi -show drun
$browser = qutebrowser
#$menu = bemenu



# ------------------------------------------------------
# Autostart
# ------------------------------------------------------

source = ~/.config/hypr/conf/autostart.conf



# ------------------------------------------------------
# Environment Variables
# ------------------------------------------------------

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = HYPRSHOT_DIR,/home/stefano/Pictures/Screenshots/

# added to enable nvidia card and second monitor display
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

cursor {
    no_hardware_cursors = true
}

env = NVD_BACKEND,direct    # added to enable VA-API Hadrware Video Acceleration (installed package libvs-nvidia-driver)


# ------------------------------------------------------
# Look and feel
# ------------------------------------------------------

source = ~/.config/hypr/conf/look_and_feel.conf



# ------------------------------------------------------
# Input and Gestures
# ------------------------------------------------------

source = ~/.config/hypr/conf/input.conf

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}



# ---------------------------------------------------------
# Keybindings
# ---------------------------------------------------------

source = ~/.config/hypr/conf/keybindings.conf



# ------------------------------------------------------
# Windows and Workspaces
# ------------------------------------------------------

source = ~/.config/hypr/conf/rules.conf
