#!/bin/bash

# script generated by ChatGPT 4 to control the temperature (nightshig) of the screen; the script gets triggered by waybar when scrolling mouse up or down 

# Path to store the current temperature
current_temp_file="/tmp/current_gammastep_temp"

# Default temperature if none is set
default_temp=4000

# Step for increasing/decreasing temperature
temp_step=100

# Read the current temperature from the file or set to default
if [ -f "$current_temp_file" ]; then
  current_temp=$(cat "$current_temp_file")
else
  current_temp=$default_temp
fi

# Function to update the temperature
update_temp() {
  new_temp=$1
  echo $new_temp > $current_temp_file
  killall gammastep
  gammastep -O $new_temp &
}

# Handle different actions
case $1 in
  toggle)
    if pgrep -x "gammastep" > /dev/null; then
      pkill gammastep
    else
      update_temp $current_temp
    fi
    ;;
  up)
    new_temp=$((current_temp + temp_step))
    update_temp $new_temp
    ;;
  down)
    new_temp=$((current_temp - temp_step))
    update_temp $new_temp
    ;;
  *)
    echo "Usage: $0 {toggle|up|down}"
    exit 1
    ;;
esac


