# See https://wiki.hyprland.org/Configuring/Monitors/
#monitor=eDP-1,1920x1080@120,0x0,1
monitor = eDP-1, 1920x1080@120, 0x0, 1

#monitor=HDMI-A-1,1920x1080@60,1920x0,1 #,mirror,eDP-1      # uncomment last part to enter mirroring mode
#monitor=HDMI-A-1,,1
#monitor = HDMI-A-1, 1920x1080@60, 0x-1080, 1 # -1080 places the monitor on top
monitor = HDMI-A-1, preferred, auto-left, 1 
