# Window and Workspaces rules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$
#windowrule = float, ^(mpv)$
#windowrule = float, ^(nannou)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

#windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

# rule used to hide the main window when screen sharing
#windowrulev2 = opacity 0.0 override, class:^(xwaylandvideobridge)$
#windowrulev2 = noanim, class:^(xwaylandvideobridge)$
#windowrulev2 = noinitialfocus, class:^(xwaylandvideobridge)$
#windowrulev2 = maxsize 1 1, class:^(xwaylandvideobridge)$
#windowrulev2 = noblur, class:^(xwaylandvideobridge)$

windowrule {
  name = qjaclctl_floating
  match:class = QjackCtl
  float = true
  #persistent_size = true
}

windowrule {
  name = mpv_floating
  match:class = mpv
  float = true
  size = 525 526
}

windowrule {
  name = "eww-exploded-pc-view"
  match:class = ^(eww-.*)$
  float = true
  pin = true
}
